kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: descheduler-role-binding 
subjects:
- kind: ServiceAccount
  name: openshift-descheduler
  namespace: openshift-kube-descheduler-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: descheduler-operator

